defaults:
  timeout: 10.0
  num: 50       
  runs: 3


harness:
  moveit:
    - moveit:RRTConnect
    - moveit:RRT
    - moveit:RRTstar
    - moveit:PRM
    - moveit:BITstar
    - moveit:EST
    - moveit:KPIECE
  curobo:          
    - curobo
  baselines:       
    - straightline
